#include "win32.h"

// Ref: https://wiki.winehq.org/List_Of_Windows_Messages
const wchar_t *
Win32MsgToText(const UINT uMsg)
{
    switch (uMsg)
    {
        case 0: return L"WM_NULL";
        case 1: return L"WM_CREATE";
        case 2: return L"WM_DESTROY";
        case 3: return L"WM_MOVE";
        case 5: return L"WM_SIZE";
        case 6: return L"WM_ACTIVATE";
        case 7: return L"WM_SETFOCUS";
        case 8: return L"WM_KILLFOCUS";
        case 10: return L"WM_ENABLE";
        case 11: return L"WM_SETREDRAW";
        case 12: return L"WM_SETTEXT";
        case 13: return L"WM_GETTEXT";
        case 14: return L"WM_GETTEXTLENGTH";
        case 15: return L"WM_PAINT";
        case 16: return L"WM_CLOSE";
        case 17: return L"WM_QUERYENDSESSION";
        case 18: return L"WM_QUIT";
        case 19: return L"WM_QUERYOPEN";
        case 20: return L"WM_ERASEBKGND";
        case 21: return L"WM_SYSCOLORCHANGE";
        case 22: return L"WM_ENDSESSION";
        case 24: return L"WM_SHOWWINDOW";
        case 25: return L"WM_CTLCOLOR";
        case 26: return L"WM_WININICHANGE";
        case 27: return L"WM_DEVMODECHANGE";
        case 28: return L"WM_ACTIVATEAPP";
        case 29: return L"WM_FONTCHANGE";
        case 30: return L"WM_TIMECHANGE";
        case 31: return L"WM_CANCELMODE";
        case 32: return L"WM_SETCURSOR";
        case 33: return L"WM_MOUSEACTIVATE";
        case 34: return L"WM_CHILDACTIVATE";
        case 35: return L"WM_QUEUESYNC";
        case 36: return L"WM_GETMINMAXINFO";
        case 38: return L"WM_PAINTICON";
        case 39: return L"WM_ICONERASEBKGND";
        case 40: return L"WM_NEXTDLGCTL";
        case 42: return L"WM_SPOOLERSTATUS";
        case 43: return L"WM_DRAWITEM";
        case 44: return L"WM_MEASUREITEM";
        case 45: return L"WM_DELETEITEM";
        case 46: return L"WM_VKEYTOITEM";
        case 47: return L"WM_CHARTOITEM";
        case 48: return L"WM_SETFONT";
        case 49: return L"WM_GETFONT";
        case 50: return L"WM_SETHOTKEY";
        case 51: return L"WM_GETHOTKEY";
        case 55: return L"WM_QUERYDRAGICON";
        case 57: return L"WM_COMPAREITEM";
        case 61: return L"WM_GETOBJECT";
        case 65: return L"WM_COMPACTING";
        case 68: return L"WM_COMMNOTIFY";
        case 70: return L"WM_WINDOWPOSCHANGING";
        case 71: return L"WM_WINDOWPOSCHANGED";
        case 72: return L"WM_POWER";
        case 73: return L"WM_COPYGLOBALDATA";
        case 74: return L"WM_COPYDATA";
        case 75: return L"WM_CANCELJOURNAL";
        case 78: return L"WM_NOTIFY";
        case 80: return L"WM_INPUTLANGCHANGEREQUEST";
        case 81: return L"WM_INPUTLANGCHANGE";
        case 82: return L"WM_TCARD";
        case 83: return L"WM_HELP";
        case 84: return L"WM_USERCHANGED";
        case 85: return L"WM_NOTIFYFORMAT";
        case 123: return L"WM_CONTEXTMENU";
        case 124: return L"WM_STYLECHANGING";
        case 125: return L"WM_STYLECHANGED";
        case 126: return L"WM_DISPLAYCHANGE";
        case 127: return L"WM_GETICON";
        case 128: return L"WM_SETICON";
        case 129: return L"WM_NCCREATE";
        case 130: return L"WM_NCDESTROY";
        case 131: return L"WM_NCCALCSIZE";
        case 132: return L"WM_NCHITTEST";
        case 133: return L"WM_NCPAINT";
        case 134: return L"WM_NCACTIVATE";
        case 135: return L"WM_GETDLGCODE";
        case 136: return L"WM_SYNCPAINT";
        case 160: return L"WM_NCMOUSEMOVE";
        case 161: return L"WM_NCLBUTTONDOWN";
        case 162: return L"WM_NCLBUTTONUP";
        case 163: return L"WM_NCLBUTTONDBLCLK";
        case 164: return L"WM_NCRBUTTONDOWN";
        case 165: return L"WM_NCRBUTTONUP";
        case 166: return L"WM_NCRBUTTONDBLCLK";
        case 167: return L"WM_NCMBUTTONDOWN";
        case 168: return L"WM_NCMBUTTONUP";
        case 169: return L"WM_NCMBUTTONDBLCLK";
        case 171: return L"WM_NCXBUTTONDOWN";
        case 172: return L"WM_NCXBUTTONUP";
        case 173: return L"WM_NCXBUTTONDBLCLK";
        case 176: return L"EM_GETSEL";
        case 177: return L"EM_SETSEL";
        case 178: return L"EM_GETRECT";
        case 179: return L"EM_SETRECT";
        case 180: return L"EM_SETRECTNP";
        case 181: return L"EM_SCROLL";
        case 182: return L"EM_LINESCROLL";
        case 183: return L"EM_SCROLLCARET";
        case 185: return L"EM_GETMODIFY";
        case 187: return L"EM_SETMODIFY";
        case 188: return L"EM_GETLINECOUNT";
        case 189: return L"EM_LINEINDEX";
        case 190: return L"EM_SETHANDLE";
        case 191: return L"EM_GETHANDLE";
        case 192: return L"EM_GETTHUMB";
        case 193: return L"EM_LINELENGTH";
        case 194: return L"EM_REPLACESEL";
        case 195: return L"EM_SETFONT";
        case 196: return L"EM_GETLINE";
        case 197: return L"EM_LIMITTEXT|EM_SETLIMITTEXT";
//        case 197: return L"EM_SETLIMITTEXT";
        case 198: return L"EM_CANUNDO";
        case 199: return L"EM_UNDO";
        case 200: return L"EM_FMTLINES";
        case 201: return L"EM_LINEFROMCHAR";
        case 202: return L"EM_SETWORDBREAK";
        case 203: return L"EM_SETTABSTOPS";
        case 204: return L"EM_SETPASSWORDCHAR";
        case 205: return L"EM_EMPTYUNDOBUFFER";
        case 206: return L"EM_GETFIRSTVISIBLELINE";
        case 207: return L"EM_SETREADONLY";
        case 209: return L"EM_SETWORDBREAKPROC";
//        case 209: return L"EM_GETWORDBREAKPROC";
        case 210: return L"EM_GETPASSWORDCHAR";
        case 211: return L"EM_SETMARGINS";
        case 212: return L"EM_GETMARGINS";
        case 213: return L"EM_GETLIMITTEXT";
        case 214: return L"EM_POSFROMCHAR";
        case 215: return L"EM_CHARFROMPOS";
        case 216: return L"EM_SETIMESTATUS";
        case 217: return L"EM_GETIMESTATUS";
        case 224: return L"SBM_SETPOS";
        case 225: return L"SBM_GETPOS";
        case 226: return L"SBM_SETRANGE";
        case 227: return L"SBM_GETRANGE";
        case 228: return L"SBM_ENABLE_ARROWS";
        case 230: return L"SBM_SETRANGEREDRAW";
        case 233: return L"SBM_SETSCROLLINFO";
        case 234: return L"SBM_GETSCROLLINFO";
        case 235: return L"SBM_GETSCROLLBARINFO";
        case 240: return L"BM_GETCHECK";
        case 241: return L"BM_SETCHECK";
        case 242: return L"BM_GETSTATE";
        case 243: return L"BM_SETSTATE";
        case 244: return L"BM_SETSTYLE";
        case 245: return L"BM_CLICK";
        case 246: return L"BM_GETIMAGE";
        case 247: return L"BM_SETIMAGE";
        case 248: return L"BM_SETDONTCLICK";
        case 255: return L"WM_INPUT";
        case 256: return L"WM_KEYDOWN";
//        case 256: return L"WM_KEYFIRST";
        case 257: return L"WM_KEYUP";
        case 258: return L"WM_CHAR";
        case 259: return L"WM_DEADCHAR";
        case 260: return L"WM_SYSKEYDOWN";
        case 261: return L"WM_SYSKEYUP";
        case 262: return L"WM_SYSCHAR";
        case 263: return L"WM_SYSDEADCHAR";
        case 265: return L"WM_UNICHAR";
//        case 265: return L"WM_WNT_CONVERTREQUESTEX";
        case 266: return L"WM_CONVERTREQUEST";
        case 267: return L"WM_CONVERTRESULT";
        case 268: return L"WM_INTERIM";
        case 269: return L"WM_IME_STARTCOMPOSITION";
        case 270: return L"WM_IME_ENDCOMPOSITION";
        case 271: return L"WM_IME_COMPOSITION";
 //       case 271: return L"WM_IME_KEYLAST";
        case 272: return L"WM_INITDIALOG";
        case 273: return L"WM_COMMAND";
        case 274: return L"WM_SYSCOMMAND";
        case 275: return L"WM_TIMER";
        case 276: return L"WM_HSCROLL";
        case 277: return L"WM_VSCROLL";
        case 278: return L"WM_INITMENU";
        case 279: return L"WM_INITMENUPOPUP";
        case 280: return L"WM_SYSTIMER";
        case 287: return L"WM_MENUSELECT";
        case 288: return L"WM_MENUCHAR";
        case 289: return L"WM_ENTERIDLE";
        case 290: return L"WM_MENURBUTTONUP";
        case 291: return L"WM_MENUDRAG";
        case 292: return L"WM_MENUGETOBJECT";
        case 293: return L"WM_UNINITMENUPOPUP";
        case 294: return L"WM_MENUCOMMAND";
        case 295: return L"WM_CHANGEUISTATE";
        case 296: return L"WM_UPDATEUISTATE";
        case 297: return L"WM_QUERYUISTATE";
        case 305: return L"WM_LBTRACKPOINT";
        case 306: return L"WM_CTLCOLORMSGBOX";
        case 307: return L"WM_CTLCOLOREDIT";
        case 308: return L"WM_CTLCOLORLISTBOX";
        case 309: return L"WM_CTLCOLORBTN";
        case 310: return L"WM_CTLCOLORDLG";
        case 311: return L"WM_CTLCOLORSCROLLBAR";
        case 312: return L"WM_CTLCOLORSTATIC";
        case 320: return L"CB_GETEDITSEL";
        case 321: return L"CB_LIMITTEXT";
        case 322: return L"CB_SETEDITSEL";
        case 323: return L"CB_ADDSTRING";
        case 324: return L"CB_DELETESTRING";
        case 325: return L"CB_DIR";
        case 326: return L"CB_GETCOUNT";
        case 327: return L"CB_GETCURSEL";
        case 328: return L"CB_GETLBTEXT";
        case 329: return L"CB_GETLBTEXTLEN";
        case 330: return L"CB_INSERTSTRING";
        case 331: return L"CB_RESETCONTENT";
        case 332: return L"CB_FINDSTRING";
        case 333: return L"CB_SELECTSTRING";
        case 334: return L"CB_SETCURSEL";
        case 335: return L"CB_SHOWDROPDOWN";
        case 336: return L"CB_GETITEMDATA";
        case 337: return L"CB_SETITEMDATA";
        case 338: return L"CB_GETDROPPEDCONTROLRECT";
        case 339: return L"CB_SETITEMHEIGHT";
        case 340: return L"CB_GETITEMHEIGHT";
        case 341: return L"CB_SETEXTENDEDUI";
        case 342: return L"CB_GETEXTENDEDUI";
        case 343: return L"CB_GETDROPPEDSTATE";
        case 344: return L"CB_FINDSTRINGEXACT";
        case 345: return L"CB_SETLOCALE";
        case 346: return L"CB_GETLOCALE";
        case 347: return L"CB_GETTOPINDEX";
        case 348: return L"CB_SETTOPINDEX";
        case 349: return L"CB_GETHORIZONTALEXTENT";
        case 350: return L"CB_SETHORIZONTALEXTENT";
        case 351: return L"CB_GETDROPPEDWIDTH";
        case 352: return L"CB_SETDROPPEDWIDTH";
        case 353: return L"CB_INITSTORAGE";
        case 355: return L"CB_MULTIPLEADDSTRING";
        case 356: return L"CB_GETCOMBOBOXINFO";
        case 357: return L"CB_MSGMAX";
//        case 512: return L"WM_MOUSEFIRST";
        case 512: return L"WM_MOUSEMOVE (WM_MOUSEFIRST)";
        case 513: return L"WM_LBUTTONDOWN";
        case 514: return L"WM_LBUTTONUP";
        case 515: return L"WM_LBUTTONDBLCLK";
        case 516: return L"WM_RBUTTONDOWN";
        case 517: return L"WM_RBUTTONUP";
        case 518: return L"WM_RBUTTONDBLCLK";
        case 519: return L"WM_MBUTTONDOWN";
        case 520: return L"WM_MBUTTONUP";
        case 521: return L"WM_MBUTTONDBLCLK";
//        case 521: return L"WM_MOUSELAST";
        case 522: return L"WM_MOUSEWHEEL (WM_MOUSELAST)";
        case 523: return L"WM_XBUTTONDOWN";
        case 524: return L"WM_XBUTTONUP";
        case 525: return L"WM_XBUTTONDBLCLK";
        case 526: return L"WM_MOUSEHWHEEL";
        case 528: return L"WM_PARENTNOTIFY";
        case 529: return L"WM_ENTERMENULOOP";
        case 530: return L"WM_EXITMENULOOP";
        case 531: return L"WM_NEXTMENU";
        case 532: return L"WM_SIZING";
        case 533: return L"WM_CAPTURECHANGED";
        case 534: return L"WM_MOVING";
        case 536: return L"WM_POWERBROADCAST";
        case 537: return L"WM_DEVICECHANGE";
        case 544: return L"WM_MDICREATE";
        case 545: return L"WM_MDIDESTROY";
        case 546: return L"WM_MDIACTIVATE";
        case 547: return L"WM_MDIRESTORE";
        case 548: return L"WM_MDINEXT";
        case 549: return L"WM_MDIMAXIMIZE";
        case 550: return L"WM_MDITILE";
        case 551: return L"WM_MDICASCADE";
        case 552: return L"WM_MDIICONARRANGE";
        case 553: return L"WM_MDIGETACTIVE";
        case 560: return L"WM_MDISETMENU";
        case 561: return L"WM_ENTERSIZEMOVE";
        case 562: return L"WM_EXITSIZEMOVE";
        case 563: return L"WM_DROPFILES";
        case 564: return L"WM_MDIREFRESHMENU";
        case 640: return L"WM_IME_REPORT";
        case 641: return L"WM_IME_SETCONTEXT";
        case 642: return L"WM_IME_NOTIFY";
        case 643: return L"WM_IME_CONTROL";
        case 644: return L"WM_IME_COMPOSITIONFULL";
        case 645: return L"WM_IME_SELECT";
        case 646: return L"WM_IME_CHAR";
        case 648: return L"WM_IME_REQUEST";
        case 656: return L"WM_IMEKEYDOWN";
//        case 656: return L"WM_IME_KEYDOWN";
        case 657: return L"WM_IMEKEYUP";
 //       case 657: return L"WM_IME_KEYUP";
        case 672: return L"WM_NCMOUSEHOVER";
        case 673: return L"WM_MOUSEHOVER";
        case 674: return L"WM_NCMOUSELEAVE";
        case 675: return L"WM_MOUSELEAVE";
        case 768: return L"WM_CUT";
        case 769: return L"WM_COPY";
        case 770: return L"WM_PASTE";
        case 771: return L"WM_CLEAR";
        case 772: return L"WM_UNDO";
        case 773: return L"WM_RENDERFORMAT";
        case 774: return L"WM_RENDERALLFORMATS";
        case 775: return L"WM_DESTROYCLIPBOARD";
        case 776: return L"WM_DRAWCLIPBOARD";
        case 777: return L"WM_PAINTCLIPBOARD";
        case 778: return L"WM_VSCROLLCLIPBOARD";
        case 779: return L"WM_SIZECLIPBOARD";
        case 780: return L"WM_ASKCBFORMATNAME";
        case 781: return L"WM_CHANGECBCHAIN";
        case 782: return L"WM_HSCROLLCLIPBOARD";
        case 783: return L"WM_QUERYNEWPALETTE";
        case 784: return L"WM_PALETTEISCHANGING";
        case 785: return L"WM_PALETTECHANGED";
        case 786: return L"WM_HOTKEY";
        case 791: return L"WM_PRINT";
        case 792: return L"WM_PRINTCLIENT";
        case 793: return L"WM_APPCOMMAND";
        case 856: return L"WM_HANDHELDFIRST";
        case 863: return L"WM_HANDHELDLAST";
        case 864: return L"WM_AFXFIRST";
        case 895: return L"WM_AFXLAST";
        case 896: return L"WM_PENWINFIRST";
        case 897: return L"WM_RCRESULT";
        case 898: return L"WM_HOOKRCRESULT";
        case 899: return L"WM_GLOBALRCCHANGE";
//        case 899: return L"WM_PENMISCINFO";
        case 900: return L"WM_SKB";
        case 901: return L"WM_HEDITCTL";
 //       case 901: return L"WM_PENCTL";
        case 902: return L"WM_PENMISC";
        case 903: return L"WM_CTLINIT";
        case 904: return L"WM_PENEVENT";
        case 911: return L"WM_PENWINLAST";
        case 1024: return L"DDM_SETFMT";
//        case 1024: return L"DM_GETDEFID";
//        case 1024: return L"NIN_SELECT";
//        case 1024: return L"TBM_GETPOS";
//        case 1024: return L"WM_PSD_PAGESETUPDLG";
//        case 1024: return L"WM_USER";
        case 1025: return L"CBEM_INSERTITEMA";
//        case 1025: return L"DDM_DRAW";
//        case 1025: return L"DM_SETDEFID";
//        case 1025: return L"HKM_SETHOTKEY";
//        case 1025: return L"PBM_SETRANGE";
//        case 1025: return L"RB_INSERTBANDA";
//        case 1025: return L"SB_SETTEXTA";
//        case 1025: return L"TB_ENABLEBUTTON";
//        case 1025: return L"TBM_GETRANGEMIN";
//        case 1025: return L"TTM_ACTIVATE";
//        case 1025: return L"WM_CHOOSEFONT_GETLOGFONT";
//        case 1025: return L"WM_PSD_FULLPAGERECT";
        case 1026: return L"CBEM_SETIMAGELIST";
//        case 1026: return L"DDM_CLOSE";
//        case 1026: return L"DM_REPOSITION";
//        case 1026: return L"HKM_GETHOTKEY";
//        case 1026: return L"PBM_SETPOS";
//        case 1026: return L"RB_DELETEBAND";
//        case 1026: return L"SB_GETTEXTA";
//        case 1026: return L"TB_CHECKBUTTON";
//        case 1026: return L"TBM_GETRANGEMAX";
//        case 1026: return L"WM_PSD_MINMARGINRECT";
        case 1027: return L"CBEM_GETIMAGELIST";
//        case 1027: return L"DDM_BEGIN";
//        case 1027: return L"HKM_SETRULES";
//        case 1027: return L"PBM_DELTAPOS";
//        case 1027: return L"RB_GETBARINFO";
//        case 1027: return L"SB_GETTEXTLENGTHA";
//        case 1027: return L"TBM_GETTIC";
//        case 1027: return L"TB_PRESSBUTTON";
//        case 1027: return L"TTM_SETDELAYTIME";
//        case 1027: return L"WM_PSD_MARGINRECT";
        case 1028: return L"CBEM_GETITEMA";
//        case 1028: return L"DDM_END";
//        case 1028: return L"PBM_SETSTEP";
//        case 1028: return L"RB_SETBARINFO";
//        case 1028: return L"SB_SETPARTS";
//        case 1028: return L"TB_HIDEBUTTON";
//        case 1028: return L"TBM_SETTIC";
//        case 1028: return L"TTM_ADDTOOLA";
//        case 1028: return L"WM_PSD_GREEKTEXTRECT";
        case 1029: return L"CBEM_SETITEMA";
//        case 1029: return L"PBM_STEPIT";
//        case 1029: return L"TB_INDETERMINATE";
//        case 1029: return L"TBM_SETPOS";
//        case 1029: return L"TTM_DELTOOLA";
//        case 1029: return L"WM_PSD_ENVSTAMPRECT";
        case 1030: return L"CBEM_GETCOMBOCONTROL";
//        case 1030: return L"PBM_SETRANGE32";
//        case 1030: return L"RB_SETBANDINFOA";
//        case 1030: return L"SB_GETPARTS";
//        case 1030: return L"TB_MARKBUTTON";
//        case 1030: return L"TBM_SETRANGE";
//        case 1030: return L"TTM_NEWTOOLRECTA";
//        case 1030: return L"WM_PSD_YAFULLPAGERECT";
        case 1031: return L"CBEM_GETEDITCONTROL";
//        case 1031: return L"PBM_GETRANGE";
//        case 1031: return L"RB_SETPARENT";
//        case 1031: return L"SB_GETBORDERS";
//        case 1031: return L"TBM_SETRANGEMIN";
//        case 1031: return L"TTM_RELAYEVENT";
        case 1032: return L"CBEM_SETEXSTYLE";
//        case 1032: return L"PBM_GETPOS";
//        case 1032: return L"RB_HITTEST";
//        case 1032: return L"SB_SETMINHEIGHT";
//        case 1032: return L"TBM_SETRANGEMAX";
//        case 1032: return L"TTM_GETTOOLINFOA";
        case 1033: return L"CBEM_GETEXSTYLE";
//        case 1033: return L"CBEM_GETEXTENDEDSTYLE";
//        case 1033: return L"PBM_SETBARCOLOR";
//        case 1033: return L"RB_GETRECT";
//        case 1033: return L"SB_SIMPLE";
//        case 1033: return L"TB_ISBUTTONENABLED";
//        case 1033: return L"TBM_CLEARTICS";
//        case 1033: return L"TTM_SETTOOLINFOA";
        case 1034: return L"CBEM_HASEDITCHANGED";
//        case 1034: return L"RB_INSERTBANDW";
//        case 1034: return L"SB_GETRECT";
//        case 1034: return L"TB_ISBUTTONCHECKED";
//        case 1034: return L"TBM_SETSEL";
//        case 1034: return L"TTM_HITTESTA";
//        case 1034: return L"WIZ_QUERYNUMPAGES";
        case 1035: return L"CBEM_INSERTITEMW";
//        case 1035: return L"RB_SETBANDINFOW";
//        case 1035: return L"SB_SETTEXTW";
//        case 1035: return L"TB_ISBUTTONPRESSED";
//        case 1035: return L"TBM_SETSELSTART";
//        case 1035: return L"TTM_GETTEXTA";
//        case 1035: return L"WIZ_NEXT";
        case 1036: return L"CBEM_SETITEMW";
//        case 1036: return L"RB_GETBANDCOUNT";
//        case 1036: return L"SB_GETTEXTLENGTHW";
//        case 1036: return L"TB_ISBUTTONHIDDEN";
//        case 1036: return L"TBM_SETSELEND";
//        case 1036: return L"TTM_UPDATETIPTEXTA";
//        case 1036: return L"WIZ_PREV";
        case 1037: return L"CBEM_GETITEMW";
//        case 1037: return L"RB_GETROWCOUNT";
//        case 1037: return L"SB_GETTEXTW";
//        case 1037: return L"TB_ISBUTTONINDETERMINATE";
//        case 1037: return L"TTM_GETTOOLCOUNT";
        case 1038: return L"CBEM_SETEXTENDEDSTYLE";
//        case 1038: return L"RB_GETROWHEIGHT";
//        case 1038: return L"SB_ISSIMPLE";
//        case 1038: return L"TB_ISBUTTONHIGHLIGHTED";
//        case 1038: return L"TBM_GETPTICS";
//        case 1038: return L"TTM_ENUMTOOLSA";
        case 1039: return L"SB_SETICON";
//        case 1039: return L"TBM_GETTICPOS";
//        case 1039: return L"TTM_GETCURRENTTOOLA";
        case 1040: return L"RB_IDTOINDEX";
//        case 1040: return L"SB_SETTIPTEXTA";
//        case 1040: return L"TBM_GETNUMTICS";
//        case 1040: return L"TTM_WINDOWFROMPOINT";
        case 1041: return L"RB_GETTOOLTIPS";
 //       case 1041: return L"SB_SETTIPTEXTW";
 //       case 1041: return L"TBM_GETSELSTART";
 //       case 1041: return L"TB_SETSTATE";
 //       case 1041: return L"TTM_TRACKACTIVATE";
        case 1042: return L"RB_SETTOOLTIPS";
//        case 1042: return L"SB_GETTIPTEXTA";
//        case 1042: return L"TB_GETSTATE";
//        case 1042: return L"TBM_GETSELEND";
//        case 1042: return L"TTM_TRACKPOSITION";
        case 1043: return L"RB_SETBKCOLOR";
//        case 1043: return L"SB_GETTIPTEXTW";
//        case 1043: return L"TB_ADDBITMAP";
//        case 1043: return L"TBM_CLEARSEL";
//        case 1043: return L"TTM_SETTIPBKCOLOR";
        case 1044: return L"RB_GETBKCOLOR";
//        case 1044: return L"SB_GETICON";
//        case 1044: return L"TB_ADDBUTTONSA";
//        case 1044: return L"TBM_SETTICFREQ";
//        case 1044: return L"TTM_SETTIPTEXTCOLOR";
        case 1045: return L"RB_SETTEXTCOLOR";
//        case 1045: return L"TB_INSERTBUTTONA";
//        case 1045: return L"TBM_SETPAGESIZE";
//        case 1045: return L"TTM_GETDELAYTIME";
        case 1046: return L"RB_GETTEXTCOLOR";
//        case 1046: return L"TB_DELETEBUTTON";
//        case 1046: return L"TBM_GETPAGESIZE";
//        case 1046: return L"TTM_GETTIPBKCOLOR";
        case 1047: return L"RB_SIZETORECT";
//        case 1047: return L"TB_GETBUTTON";
//        case 1047: return L"TBM_SETLINESIZE";
//        case 1047: return L"TTM_GETTIPTEXTCOLOR";
        case 1048: return L"RB_BEGINDRAG";
//        case 1048: return L"TB_BUTTONCOUNT";
//        case 1048: return L"TBM_GETLINESIZE";
//        case 1048: return L"TTM_SETMAXTIPWIDTH";
        case 1049: return L"RB_ENDDRAG";
//        case 1049: return L"TB_COMMANDTOINDEX";
//        case 1049: return L"TBM_GETTHUMBRECT";
//        case 1049: return L"TTM_GETMAXTIPWIDTH";
        case 1050: return L"RB_DRAGMOVE";
//        case 1050: return L"TBM_GETCHANNELRECT";
//        case 1050: return L"TB_SAVERESTOREA";
//        case 1050: return L"TTM_SETMARGIN";
        case 1051: return L"RB_GETBARHEIGHT";
//        case 1051: return L"TB_CUSTOMIZE";
//        case 1051: return L"TBM_SETTHUMBLENGTH";
//        case 1051: return L"TTM_GETMARGIN";
        case 1052: return L"RB_GETBANDINFOW";
//        case 1052: return L"TB_ADDSTRINGA";
//        case 1052: return L"TBM_GETTHUMBLENGTH";
//        case 1052: return L"TTM_POP";
        case 1053: return L"RB_GETBANDINFOA";
//        case 1053: return L"TB_GETITEMRECT";
//        case 1053: return L"TBM_SETTOOLTIPS";
//        case 1053: return L"TTM_UPDATE";
        case 1054: return L"RB_MINIMIZEBAND";
//        case 1054: return L"TB_BUTTONSTRUCTSIZE";
//        case 1054: return L"TBM_GETTOOLTIPS";
//        case 1054: return L"TTM_GETBUBBLESIZE";
        case 1055: return L"RB_MAXIMIZEBAND";
//        case 1055: return L"TBM_SETTIPSIDE";
//        case 1055: return L"TB_SETBUTTONSIZE";
//        case 1055: return L"TTM_ADJUSTRECT";
        case 1056: return L"TBM_SETBUDDY";
//        case 1056: return L"TB_SETBITMAPSIZE";
//        case 1056: return L"TTM_SETTITLEA";
        case 1057: return L"MSG_FTS_JUMP_VA";
//        case 1057: return L"TB_AUTOSIZE";
//        case 1057: return L"TBM_GETBUDDY";
//        case 1057: return L"TTM_SETTITLEW";
        case 1058: return L"RB_GETBANDBORDERS";
        case 1059: return L"MSG_FTS_JUMP_QWORD";
//        case 1059: return L"RB_SHOWBAND";
//        case 1059: return L"TB_GETTOOLTIPS";
        case 1060: return L"MSG_REINDEX_REQUEST";
//        case 1060: return L"TB_SETTOOLTIPS";
        case 1061: return L"MSG_FTS_WHERE_IS_IT";
//        case 1061: return L"RB_SETPALETTE";
//        case 1061: return L"TB_SETPARENT";
        case 1062: return L"RB_GETPALETTE";
        case 1063: return L"RB_MOVEBAND";
//        case 1063: return L"TB_SETROWS";
        case 1064: return L"TB_GETROWS";
        case 1065: return L"TB_GETBITMAPFLAGS";
        case 1066: return L"TB_SETCMDID";
        case 1067: return L"RB_PUSHCHEVRON";
//        case 1067: return L"TB_CHANGEBITMAP";
        case 1068: return L"TB_GETBITMAP";
        case 1069: return L"MSG_GET_DEFFONT";
//        case 1069: return L"TB_GETBUTTONTEXTA";
        case 1070: return L"TB_REPLACEBITMAP";
        case 1071: return L"TB_SETINDENT";
        case 1072: return L"TB_SETIMAGELIST";
        case 1073: return L"TB_GETIMAGELIST";
        case 1074: return L"TB_LOADIMAGES";
//        case 1074: return L"EM_CANPASTE";
//        case 1074: return L"TTM_ADDTOOLW";
        case 1075: return L"EM_DISPLAYBAND";
//        case 1075: return L"TB_GETRECT";
//        case 1075: return L"TTM_DELTOOLW";
        case 1076: return L"EM_EXGETSEL";
//        case 1076: return L"TB_SETHOTIMAGELIST";
//        case 1076: return L"TTM_NEWTOOLRECTW";
        case 1077: return L"EM_EXLIMITTEXT";
//        case 1077: return L"TB_GETHOTIMAGELIST";
//        case 1077: return L"TTM_GETTOOLINFOW";
        case 1078: return L"EM_EXLINEFROMCHAR";
//        case 1078: return L"TB_SETDISABLEDIMAGELIST";
//        case 1078: return L"TTM_SETTOOLINFOW";
        case 1079: return L"EM_EXSETSEL";
//        case 1079: return L"TB_GETDISABLEDIMAGELIST";
//        case 1079: return L"TTM_HITTESTW";
        case 1080: return L"EM_FINDTEXT";
//        case 1080: return L"TB_SETSTYLE";
//        case 1080: return L"TTM_GETTEXTW";
        case 1081: return L"EM_FORMATRANGE";
//        case 1081: return L"TB_GETSTYLE";
//        case 1081: return L"TTM_UPDATETIPTEXTW";
        case 1082: return L"EM_GETCHARFORMAT";
//        case 1082: return L"TB_GETBUTTONSIZE";
//        case 1082: return L"TTM_ENUMTOOLSW";
        case 1083: return L"EM_GETEVENTMASK";
//        case 1083: return L"TB_SETBUTTONWIDTH";
//        case 1083: return L"TTM_GETCURRENTTOOLW";
        case 1084: return L"EM_GETOLEINTERFACE";
//        case 1084: return L"TB_SETMAXTEXTROWS";
        case 1085: return L"EM_GETPARAFORMAT";
//        case 1085: return L"TB_GETTEXTROWS";
        case 1086: return L"EM_GETSELTEXT";
//        case 1086: return L"TB_GETOBJECT";
        case 1087: return L"EM_HIDESELECTION";
//        case 1087: return L"TB_GETBUTTONINFOW";
        case 1088: return L"EM_PASTESPECIAL";
//        case 1088: return L"TB_SETBUTTONINFOW";
        case 1089: return L"EM_REQUESTRESIZE";
//        case 1089: return L"TB_GETBUTTONINFOA";
        case 1090: return L"EM_SELECTIONTYPE";
//        case 1090: return L"TB_SETBUTTONINFOA";
        case 1091: return L"EM_SETBKGNDCOLOR";
//        case 1091: return L"TB_INSERTBUTTONW";
        case 1092: return L"EM_SETCHARFORMAT";
//        case 1092: return L"TB_ADDBUTTONSW";
        case 1093: return L"EM_SETEVENTMASK";
//        case 1093: return L"TB_HITTEST";
        case 1094: return L"EM_SETOLECALLBACK";
//        case 1094: return L"TB_SETDRAWTEXTFLAGS";
        case 1095: return L"EM_SETPARAFORMAT";
//        case 1095: return L"TB_GETHOTITEM";
        case 1096: return L"EM_SETTARGETDEVICE";
//        case 1096: return L"TB_SETHOTITEM";
        case 1097: return L"EM_STREAMIN";
//        case 1097: return L"TB_SETANCHORHIGHLIGHT";
        case 1098: return L"EM_STREAMOUT";
//        case 1098: return L"TB_GETANCHORHIGHLIGHT";
        case 1099: return L"EM_GETTEXTRANGE";
//        case 1099: return L"TB_GETBUTTONTEXTW";
        case 1100: return L"EM_FINDWORDBREAK";
//        case 1100: return L"TB_SAVERESTOREW";
        case 1101: return L"EM_SETOPTIONS";
//        case 1101: return L"TB_ADDSTRINGW";
        case 1102: return L"EM_GETOPTIONS";
//        case 1102: return L"TB_MAPACCELERATORA";
        case 1103: return L"EM_FINDTEXTEX";
//        case 1103: return L"TB_GETINSERTMARK";
        case 1104: return L"EM_GETWORDBREAKPROCEX";
//        case 1104: return L"TB_SETINSERTMARK";
        case 1105: return L"EM_SETWORDBREAKPROCEX";
//        case 1105: return L"TB_INSERTMARKHITTEST";
        case 1106: return L"EM_SETUNDOLIMIT";
//        case 1106: return L"TB_MOVEBUTTON";
        case 1107: return L"TB_GETMAXSIZE";
        case 1108: return L"EM_REDO";
//        case 1108: return L"TB_SETEXTENDEDSTYLE";
        case 1109: return L"EM_CANREDO";
//        case 1109: return L"TB_GETEXTENDEDSTYLE";
        case 1110: return L"EM_GETUNDONAME";
//        case 1110: return L"TB_GETPADDING";
        case 1111: return L"EM_GETREDONAME";
//        case 1111: return L"TB_SETPADDING";
        case 1112: return L"EM_STOPGROUPTYPING";
//        case 1112: return L"TB_SETINSERTMARKCOLOR";
        case 1113: return L"EM_SETTEXTMODE";
//        case 1113: return L"TB_GETINSERTMARKCOLOR";
        case 1114: return L"EM_GETTEXTMODE";
//        case 1114: return L"TB_MAPACCELERATORW";
        case 1115: return L"EM_AUTOURLDETECT";
//        case 1115: return L"TB_GETSTRINGW";
        case 1116: return L"EM_GETAUTOURLDETECT";
//        case 1116: return L"TB_GETSTRINGA";
        case 1117: return L"EM_SETPALETTE";
        case 1118: return L"EM_GETTEXTEX";
        case 1119: return L"EM_GETTEXTLENGTHEX";
        case 1120: return L"EM_SHOWSCROLLBAR";
        case 1121: return L"EM_SETTEXTEX";
        case 1123: return L"TAPI_REPLY";
        case 1124: return L"ACM_OPENA";
//        case 1124: return L"BFFM_SETSTATUSTEXTA";
//        case 1124: return L"CDM_FIRST";
//        case 1124: return L"CDM_GETSPEC";
//        case 1124: return L"EM_SETPUNCTUATION";
//        case 1124: return L"IPM_CLEARADDRESS";
//        case 1124: return L"WM_CAP_UNICODE_START";
        case 1125: return L"ACM_PLAY";
//        case 1125: return L"BFFM_ENABLEOK";
//        case 1125: return L"CDM_GETFILEPATH";
//        case 1125: return L"EM_GETPUNCTUATION";
//        case 1125: return L"IPM_SETADDRESS";
//        case 1125: return L"PSM_SETCURSEL";
//        case 1125: return L"UDM_SETRANGE";
//        case 1125: return L"WM_CHOOSEFONT_SETLOGFONT";
        case 1126: return L"ACM_STOP";
//        case 1126: return L"BFFM_SETSELECTIONA";
//        case 1126: return L"CDM_GETFOLDERPATH";
//        case 1126: return L"EM_SETWORDWRAPMODE";
//        case 1126: return L"IPM_GETADDRESS";
//        case 1126: return L"PSM_REMOVEPAGE";
//        case 1126: return L"UDM_GETRANGE";
//        case 1126: return L"WM_CAP_SET_CALLBACK_ERRORW";
//        case 1126: return L"WM_CHOOSEFONT_SETFLAGS";
        case 1127: return L"ACM_OPENW";
//        case 1127: return L"BFFM_SETSELECTIONW";
//        case 1127: return L"CDM_GETFOLDERIDLIST";
//        case 1127: return L"EM_GETWORDWRAPMODE";
//        case 1127: return L"IPM_SETRANGE";
//        case 1127: return L"PSM_ADDPAGE";
//        case 1127: return L"UDM_SETPOS";
//        case 1127: return L"WM_CAP_SET_CALLBACK_STATUSW";
        case 1128: return L"BFFM_SETSTATUSTEXTW";
//        case 1128: return L"CDM_SETCONTROLTEXT";
//        case 1128: return L"EM_SETIMECOLOR";
//        case 1128: return L"IPM_SETFOCUS";
//        case 1128: return L"PSM_CHANGED";
//        case 1128: return L"UDM_GETPOS";
        case 1129: return L"CDM_HIDECONTROL";
//        case 1129: return L"EM_GETIMECOLOR";
//        case 1129: return L"IPM_ISBLANK";
//        case 1129: return L"PSM_RESTARTWINDOWS";
//        case 1129: return L"UDM_SETBUDDY";
        case 1130: return L"CDM_SETDEFEXT";
//        case 1130: return L"EM_SETIMEOPTIONS";
//        case 1130: return L"PSM_REBOOTSYSTEM";
//        case 1130: return L"UDM_GETBUDDY";
        case 1131: return L"EM_GETIMEOPTIONS";
//        case 1131: return L"PSM_CANCELTOCLOSE";
//        case 1131: return L"UDM_SETACCEL";
        case 1132: return L"EM_CONVPOSITION";
//        case 1132: return L"EM_CONVPOSITION";
//        case 1132: return L"PSM_QUERYSIBLINGS";
//        case 1132: return L"UDM_GETACCEL";
        case 1133: return L"MCIWNDM_GETZOOM";
//        case 1133: return L"PSM_UNCHANGED";
//        case 1133: return L"UDM_SETBASE";
        case 1134: return L"PSM_APPLY";
//        case 1134: return L"UDM_GETBASE";
        case 1135: return L"PSM_SETTITLEA";
//        case 1135: return L"UDM_SETRANGE32";
        case 1136: return L"PSM_SETWIZBUTTONS";
//        case 1136: return L"UDM_GETRANGE32";
//        case 1136: return L"WM_CAP_DRIVER_GET_NAMEW";
        case 1137: return L"PSM_PRESSBUTTON";
//        case 1137: return L"UDM_SETPOS32";
//        case 1137: return L"WM_CAP_DRIVER_GET_VERSIONW";
        case 1138: return L"PSM_SETCURSELID";
//        case 1138: return L"UDM_GETPOS32";
        case 1139: return L"PSM_SETFINISHTEXTA";
        case 1140: return L"PSM_GETTABCONTROL";
        case 1141: return L"PSM_ISDIALOGMESSAGE";
        case 1142: return L"MCIWNDM_REALIZE";
//        case 1142: return L"PSM_GETCURRENTPAGEHWND";
        case 1143: return L"MCIWNDM_SETTIMEFORMATA";
//        case 1143: return L"PSM_INSERTPAGE";
        case 1144: return L"EM_SETLANGOPTIONS";
//        case 1144: return L"MCIWNDM_GETTIMEFORMATA";
//        case 1144: return L"PSM_SETTITLEW";
//        case 1144: return L"WM_CAP_FILE_SET_CAPTURE_FILEW";
        case 1145: return L"EM_GETLANGOPTIONS";
//        case 1145: return L"MCIWNDM_VALIDATEMEDIA";
//        case 1145: return L"PSM_SETFINISHTEXTW";
//        case 1145: return L"WM_CAP_FILE_GET_CAPTURE_FILEW";
        case 1146: return L"EM_GETIMECOMPMODE";
        case 1147: return L"EM_FINDTEXTW";
//        case 1147: return L"MCIWNDM_PLAYTO";
//        case 1147: return L"WM_CAP_FILE_SAVEASW";
        case 1148: return L"EM_FINDTEXTEXW";
//        case 1148: return L"MCIWNDM_GETFILENAMEA";
        case 1149: return L"EM_RECONVERSION";
//        case 1149: return L"MCIWNDM_GETDEVICEA";
//        case 1149: return L"PSM_SETHEADERTITLEA";
//        case 1149: return L"WM_CAP_FILE_SAVEDIBW";
        case 1150: return L"EM_SETIMEMODEBIAS";
//        case 1150: return L"MCIWNDM_GETPALETTE";
//        case 1150: return L"PSM_SETHEADERTITLEW";
        case 1151: return L"EM_GETIMEMODEBIAS";
//        case 1151: return L"MCIWNDM_SETPALETTE";
//        case 1151: return L"PSM_SETHEADERSUBTITLEA";
        case 1152: return L"MCIWNDM_GETERRORA";
//        case 1152: return L"PSM_SETHEADERSUBTITLEW";
        case 1153: return L"PSM_HWNDTOINDEX";
        case 1154: return L"PSM_INDEXTOHWND";
        case 1155: return L"MCIWNDM_SETINACTIVETIMER";
//        case 1155: return L"PSM_PAGETOINDEX";
        case 1156: return L"PSM_INDEXTOPAGE";
        case 1157: return L"DL_BEGINDRAG";
//        case 1157: return L"MCIWNDM_GETINACTIVETIMER";
//        case 1157: return L"PSM_IDTOINDEX";
        case 1158: return L"DL_DRAGGING";
//        case 1158: return L"PSM_INDEXTOID";
        case 1159: return L"DL_DROPPED";
//        case 1159: return L"PSM_GETRESULT";
        case 1160: return L"DL_CANCELDRAG";
//        case 1160: return L"PSM_RECALCPAGESIZES";
        case 1164: return L"MCIWNDM_GET_SOURCE";
        case 1165: return L"MCIWNDM_PUT_SOURCE";
        case 1166: return L"MCIWNDM_GET_DEST";
        case 1167: return L"MCIWNDM_PUT_DEST";
        case 1168: return L"MCIWNDM_CAN_PLAY";
        case 1169: return L"MCIWNDM_CAN_WINDOW";
        case 1170: return L"MCIWNDM_CAN_RECORD";
        case 1171: return L"MCIWNDM_CAN_SAVE";
        case 1172: return L"MCIWNDM_CAN_EJECT";
        case 1173: return L"MCIWNDM_CAN_CONFIG";
        case 1174: return L"IE_GETINK";
//        case 1174: return L"IE_MSGFIRST";
//        case 1174: return L"MCIWNDM_PALETTEKICK";
        case 1175: return L"IE_SETINK";
        case 1176: return L"IE_GETPENTIP";
        case 1177: return L"IE_SETPENTIP";
        case 1178: return L"IE_GETERASERTIP";
        case 1179: return L"IE_SETERASERTIP";
        case 1180: return L"IE_GETBKGND";
        case 1181: return L"IE_SETBKGND";
        case 1182: return L"IE_GETGRIDORIGIN";
        case 1183: return L"IE_SETGRIDORIGIN";
        case 1184: return L"IE_GETGRIDPEN";
        case 1185: return L"IE_SETGRIDPEN";
        case 1186: return L"IE_GETGRIDSIZE";
        case 1187: return L"IE_SETGRIDSIZE";
        case 1188: return L"IE_GETMODE";
        case 1189: return L"IE_SETMODE";
        case 1190: return L"IE_GETINKRECT";
//        case 1190: return L"WM_CAP_SET_MCI_DEVICEW";
        case 1191: return L"WM_CAP_GET_MCI_DEVICEW";
        case 1204: return L"WM_CAP_PAL_OPENW";
        case 1205: return L"WM_CAP_PAL_SAVEW";
        case 1208: return L"IE_GETAPPDATA";
        case 1209: return L"IE_SETAPPDATA";
        case 1210: return L"IE_GETDRAWOPTS";
        case 1211: return L"IE_SETDRAWOPTS";
        case 1212: return L"IE_GETFORMAT";
        case 1213: return L"IE_SETFORMAT";
        case 1214: return L"IE_GETINKINPUT";
        case 1215: return L"IE_SETINKINPUT";
        case 1216: return L"IE_GETNOTIFY";
        case 1217: return L"IE_SETNOTIFY";
        case 1218: return L"IE_GETRECOG";
        case 1219: return L"IE_SETRECOG";
        case 1220: return L"IE_GETSECURITY";
        case 1221: return L"IE_SETSECURITY";
        case 1222: return L"IE_GETSEL";
        case 1223: return L"IE_SETSEL";
        case 1224: return L"CDM_LAST";
//        case 1224: return L"EM_SETBIDIOPTIONS";
//        case 1224: return L"IE_DOCOMMAND";
//        case 1224: return L"MCIWNDM_NOTIFYMODE";
        case 1225: return L"EM_GETBIDIOPTIONS";
//        case 1225: return L"IE_GETCOMMAND";
        case 1226: return L"EM_SETTYPOGRAPHYOPTIONS";
//        case 1226: return L"IE_GETCOUNT";
        case 1227: return L"EM_GETTYPOGRAPHYOPTIONS";
//        case 1227: return L"IE_GETGESTURE";
//        case 1227: return L"MCIWNDM_NOTIFYMEDIA";
        case 1228: return L"EM_SETEDITSTYLE";
//        case 1228: return L"IE_GETMENU";
        case 1229: return L"EM_GETEDITSTYLE";
//        case 1229: return L"IE_GETPAINTDC";
//        case 1229: return L"MCIWNDM_NOTIFYERROR";
        case 1230: return L"IE_GETPDEVENT";
        case 1231: return L"IE_GETSELCOUNT";
        case 1232: return L"IE_GETSELITEMS";
        case 1233: return L"IE_GETSTYLE";
        case 1243: return L"MCIWNDM_SETTIMEFORMATW";
        case 1244: return L"EM_OUTLINE";
//        case 1244: return L"MCIWNDM_GETTIMEFORMATW";
        case 1245: return L"EM_GETSCROLLPOS";
        case 1246: return L"EM_SETSCROLLPOS";
//        case 1246: return L"EM_SETSCROLLPOS";
        case 1247: return L"EM_SETFONTSIZE";
        case 1248: return L"EM_GETZOOM";
//        case 1248: return L"MCIWNDM_GETFILENAMEW";
        case 1249: return L"EM_SETZOOM";
//        case 1249: return L"MCIWNDM_GETDEVICEW";
        case 1250: return L"EM_GETVIEWKIND";
        case 1251: return L"EM_SETVIEWKIND";
        case 1252: return L"EM_GETPAGE";
//        case 1252: return L"MCIWNDM_GETERRORW";
        case 1253: return L"EM_SETPAGE";
        case 1254: return L"EM_GETHYPHENATEINFO";
        case 1255: return L"EM_SETHYPHENATEINFO";
        case 1259: return L"EM_GETPAGEROTATE";
        case 1260: return L"EM_SETPAGEROTATE";
        case 1261: return L"EM_GETCTFMODEBIAS";
        case 1262: return L"EM_SETCTFMODEBIAS";
        case 1264: return L"EM_GETCTFOPENSTATUS";
        case 1265: return L"EM_SETCTFOPENSTATUS";
        case 1266: return L"EM_GETIMECOMPTEXT";
        case 1267: return L"EM_ISIME";
        case 1268: return L"EM_GETIMEPROPERTY";
        case 1293: return L"EM_GETQUERYRTFOBJ";
        case 1294: return L"EM_SETQUERYRTFOBJ";
        case 1536: return L"FM_GETFOCUS";
        case 1537: return L"FM_GETDRIVEINFOA";
        case 1538: return L"FM_GETSELCOUNT";
        case 1539: return L"FM_GETSELCOUNTLFN";
        case 1540: return L"FM_GETFILESELA";
        case 1541: return L"FM_GETFILESELLFNA";
        case 1542: return L"FM_REFRESH_WINDOWS";
        case 1543: return L"FM_RELOAD_EXTENSIONS";
        case 1553: return L"FM_GETDRIVEINFOW";
        case 1556: return L"FM_GETFILESELW";
        case 1557: return L"FM_GETFILESELLFNW";
        case 1625: return L"WLX_WM_SAS";
        case 2024: return L"SM_GETSELCOUNT";
//        case 2024: return L"UM_GETSELCOUNT";
//        case 2024: return L"WM_CPL_LAUNCH";
        case 2025: return L"SM_GETSERVERSELA";
//        case 2025: return L"UM_GETUSERSELA";
//        case 2025: return L"WM_CPL_LAUNCHED";
        case 2026: return L"SM_GETSERVERSELW";
//        case 2026: return L"UM_GETUSERSELW";
        case 2027: return L"SM_GETCURFOCUSA";
//        case 2027: return L"UM_GETGROUPSELA";
        case 2028: return L"SM_GETCURFOCUSW";
//        case 2028: return L"UM_GETGROUPSELW";
        case 2029: return L"SM_GETOPTIONS";
//        case 2029: return L"UM_GETCURFOCUSA";
        case 2030: return L"UM_GETCURFOCUSW";
        case 2031: return L"UM_GETOPTIONS";
        case 2032: return L"UM_GETOPTIONS2";
        case 4096: return L"LVM_FIRST";
//        case 4096: return L"LVM_GETBKCOLOR";
        case 4097: return L"LVM_SETBKCOLOR";
        case 4098: return L"LVM_GETIMAGELIST";
        case 4099: return L"LVM_SETIMAGELIST";
        case 4100: return L"LVM_GETITEMCOUNT";
        case 4101: return L"LVM_GETITEMA";
        case 4102: return L"LVM_SETITEMA";
        case 4103: return L"LVM_INSERTITEMA";
        case 4104: return L"LVM_DELETEITEM";
        case 4105: return L"LVM_DELETEALLITEMS";
        case 4106: return L"LVM_GETCALLBACKMASK";
        case 4107: return L"LVM_SETCALLBACKMASK";
        case 4108: return L"LVM_GETNEXTITEM";
        case 4109: return L"LVM_FINDITEMA";
        case 4110: return L"LVM_GETITEMRECT";
        case 4111: return L"LVM_SETITEMPOSITION";
        case 4112: return L"LVM_GETITEMPOSITION";
        case 4113: return L"LVM_GETSTRINGWIDTHA";
        case 4114: return L"LVM_HITTEST";
        case 4115: return L"LVM_ENSUREVISIBLE";
        case 4116: return L"LVM_SCROLL";
        case 4117: return L"LVM_REDRAWITEMS";
        case 4118: return L"LVM_ARRANGE";
        case 4119: return L"LVM_EDITLABELA";
        case 4120: return L"LVM_GETEDITCONTROL";
        case 4121: return L"LVM_GETCOLUMNA";
        case 4122: return L"LVM_SETCOLUMNA";
        case 4123: return L"LVM_INSERTCOLUMNA";
        case 4124: return L"LVM_DELETECOLUMN";
        case 4125: return L"LVM_GETCOLUMNWIDTH";
        case 4126: return L"LVM_SETCOLUMNWIDTH";
        case 4127: return L"LVM_GETHEADER";
        case 4129: return L"LVM_CREATEDRAGIMAGE";
        case 4130: return L"LVM_GETVIEWRECT";
        case 4131: return L"LVM_GETTEXTCOLOR";
        case 4132: return L"LVM_SETTEXTCOLOR";
        case 4133: return L"LVM_GETTEXTBKCOLOR";
        case 4134: return L"LVM_SETTEXTBKCOLOR";
        case 4135: return L"LVM_GETTOPINDEX";
        case 4136: return L"LVM_GETCOUNTPERPAGE";
        case 4137: return L"LVM_GETORIGIN";
        case 4138: return L"LVM_UPDATE";
        case 4139: return L"LVM_SETITEMSTATE";
        case 4140: return L"LVM_GETITEMSTATE";
        case 4141: return L"LVM_GETITEMTEXTA";
        case 4142: return L"LVM_SETITEMTEXTA";
        case 4143: return L"LVM_SETITEMCOUNT";
        case 4144: return L"LVM_SORTITEMS";
        case 4145: return L"LVM_SETITEMPOSITION32";
        case 4146: return L"LVM_GETSELECTEDCOUNT";
        case 4147: return L"LVM_GETITEMSPACING";
        case 4148: return L"LVM_GETISEARCHSTRINGA";
        case 4149: return L"LVM_SETICONSPACING";
        case 4150: return L"LVM_SETEXTENDEDLISTVIEWSTYLE";
        case 4151: return L"LVM_GETEXTENDEDLISTVIEWSTYLE";
        case 4152: return L"LVM_GETSUBITEMRECT";
        case 4153: return L"LVM_SUBITEMHITTEST";
        case 4154: return L"LVM_SETCOLUMNORDERARRAY";
        case 4155: return L"LVM_GETCOLUMNORDERARRAY";
        case 4156: return L"LVM_SETHOTITEM";
        case 4157: return L"LVM_GETHOTITEM";
        case 4158: return L"LVM_SETHOTCURSOR";
        case 4159: return L"LVM_GETHOTCURSOR";
        case 4160: return L"LVM_APPROXIMATEVIEWRECT";
        case 4161: return L"LVM_SETWORKAREAS";
        case 4162: return L"LVM_GETSELECTIONMARK";
        case 4163: return L"LVM_SETSELECTIONMARK";
        case 4164: return L"LVM_SETBKIMAGEA";
        case 4165: return L"LVM_GETBKIMAGEA";
        case 4166: return L"LVM_GETWORKAREAS";
        case 4167: return L"LVM_SETHOVERTIME";
        case 4168: return L"LVM_GETHOVERTIME";
        case 4169: return L"LVM_GETNUMBEROFWORKAREAS";
        case 4170: return L"LVM_SETTOOLTIPS";
        case 4171: return L"LVM_GETITEMW";
        case 4172: return L"LVM_SETITEMW";
        case 4173: return L"LVM_INSERTITEMW";
        case 4174: return L"LVM_GETTOOLTIPS";
        case 4179: return L"LVM_FINDITEMW";
        case 4183: return L"LVM_GETSTRINGWIDTHW";
        case 4191: return L"LVM_GETCOLUMNW";
        case 4192: return L"LVM_SETCOLUMNW";
        case 4193: return L"LVM_INSERTCOLUMNW";
        case 4211: return L"LVM_GETITEMTEXTW";
        case 4212: return L"LVM_SETITEMTEXTW";
        case 4213: return L"LVM_GETISEARCHSTRINGW";
        case 4214: return L"LVM_EDITLABELW";
        case 4235: return L"LVM_GETBKIMAGEW";
        case 4236: return L"LVM_SETSELECTEDCOLUMN";
        case 4237: return L"LVM_SETTILEWIDTH";
        case 4238: return L"LVM_SETVIEW";
        case 4239: return L"LVM_GETVIEW";
        case 4241: return L"LVM_INSERTGROUP";
        case 4243: return L"LVM_SETGROUPINFO";
        case 4245: return L"LVM_GETGROUPINFO";
        case 4246: return L"LVM_REMOVEGROUP";
        case 4247: return L"LVM_MOVEGROUP";
        case 4250: return L"LVM_MOVEITEMTOGROUP";
        case 4251: return L"LVM_SETGROUPMETRICS";
        case 4252: return L"LVM_GETGROUPMETRICS";
        case 4253: return L"LVM_ENABLEGROUPVIEW";
        case 4254: return L"LVM_SORTGROUPS";
        case 4255: return L"LVM_INSERTGROUPSORTED";
        case 4256: return L"LVM_REMOVEALLGROUPS";
        case 4257: return L"LVM_HASGROUP";
        case 4258: return L"LVM_SETTILEVIEWINFO";
        case 4259: return L"LVM_GETTILEVIEWINFO";
        case 4260: return L"LVM_SETTILEINFO";
        case 4261: return L"LVM_GETTILEINFO";
        case 4262: return L"LVM_SETINSERTMARK";
        case 4263: return L"LVM_GETINSERTMARK";
        case 4264: return L"LVM_INSERTMARKHITTEST";
        case 4265: return L"LVM_GETINSERTMARKRECT";
        case 4266: return L"LVM_SETINSERTMARKCOLOR";
        case 4267: return L"LVM_GETINSERTMARKCOLOR";
        case 4269: return L"LVM_SETINFOTIP";
        case 4270: return L"LVM_GETSELECTEDCOLUMN";
        case 4271: return L"LVM_ISGROUPVIEWENABLED";
        case 4272: return L"LVM_GETOUTLINECOLOR";
        case 4273: return L"LVM_SETOUTLINECOLOR";
        case 4275: return L"LVM_CANCELEDITLABEL";
        case 4276: return L"LVM_MAPINDEXTOID";
        case 4277: return L"LVM_MAPIDTOINDEX";
        case 4278: return L"LVM_ISITEMVISIBLE";
        case 4300: return L"LVM_GETEMPTYTEXT";
        case 4301: return L"LVM_GETFOOTERRECT";
        case 4302: return L"LVM_GETFOOTERINFO";
        case 4303: return L"LVM_GETFOOTERITEMRECT";
        case 4304: return L"LVM_GETFOOTERITEM";
        case 4305: return L"LVM_GETITEMINDEXRECT";
        case 4306: return L"LVM_SETITEMINDEXSTATE";
        case 4307: return L"LVM_GETNEXTITEMINDEX";
        case 8192: return L"OCM__BASE";
        case 8197: return L"LVM_SETUNICODEFORMAT";
        case 8198: return L"LVM_GETUNICODEFORMAT";
        case 8217: return L"OCM_CTLCOLOR";
        case 8235: return L"OCM_DRAWITEM";
        case 8236: return L"OCM_MEASUREITEM";
        case 8237: return L"OCM_DELETEITEM";
        case 8238: return L"OCM_VKEYTOITEM";
        case 8239: return L"OCM_CHARTOITEM";
        case 8249: return L"OCM_COMPAREITEM";
        case 8270: return L"OCM_NOTIFY";
        case 8465: return L"OCM_COMMAND";
        case 8468: return L"OCM_HSCROLL";
        case 8469: return L"OCM_VSCROLL";
        case 8498: return L"OCM_CTLCOLORMSGBOX";
        case 8499: return L"OCM_CTLCOLOREDIT";
        case 8500: return L"OCM_CTLCOLORLISTBOX";
        case 8501: return L"OCM_CTLCOLORBTN";
        case 8502: return L"OCM_CTLCOLORDLG";
        case 8503: return L"OCM_CTLCOLORSCROLLBAR";
        case 8504: return L"OCM_CTLCOLORSTATIC";
        case 8720: return L"OCM_PARENTNOTIFY";
        case 32768: return L"WM_APP";
        case 52429: return L"WM_RASDIALEVENT";
        default: return L"???";
    }
}

